param(
  [string]$ReleaseTag,
  [string]$RegistryPrefix = 'myems',
  [string]$EmqxImage = 'emqx/emqx:latest',
  [string]$OutputDir,
  [switch]$SkipSave
)

$ErrorActionPreference = 'Stop'

function Assert-CommandExists {
  param(
    [Parameter(Mandatory = $true)]
    [string]$Name
  )

  if (-not (Get-Command $Name -ErrorAction SilentlyContinue)) {
    throw "Required command '$Name' was not found in PATH. Run this script on a build machine with Docker installed."
  }
}

function Get-ImageName {
  param(
    [Parameter(Mandatory = $true)]
    [string]$Repository,
    [Parameter(Mandatory = $true)]
    [string]$Tag
  )

  $normalizedPrefix = $RegistryPrefix.TrimEnd('/')
  if ([string]::IsNullOrWhiteSpace($normalizedPrefix)) {
    return "${Repository}:${Tag}"
  }

  return "${normalizedPrefix}/${Repository}:${Tag}"
}

Assert-CommandExists -Name 'git'
Assert-CommandExists -Name 'docker'
Assert-CommandExists -Name 'docker-compose'

$repoRoot = Split-Path -Parent $PSScriptRoot
Set-Location $repoRoot

if ([string]::IsNullOrWhiteSpace($ReleaseTag)) {
  $ReleaseTag = ((git rev-parse --short HEAD).Trim())
}

if ([string]::IsNullOrWhiteSpace($ReleaseTag)) {
  throw 'Unable to determine release tag. Pass -ReleaseTag explicitly.'
}

if ([string]::IsNullOrWhiteSpace($OutputDir)) {
  $OutputDir = Join-Path $repoRoot (Join-Path 'release-artifacts' $ReleaseTag)
}

$null = New-Item -ItemType Directory -Path $OutputDir -Force

$composeFile = Join-Path $repoRoot 'others\docker-compose-on-linux.yml'
if (-not (Test-Path $composeFile)) {
  throw 'Compose file others\docker-compose-on-linux.yml was not found.'
}

$imageMap = [ordered]@{
  MYEMS_EMQX_IMAGE = $EmqxImage
  MYEMS_API_IMAGE = Get-ImageName -Repository 'api' -Tag $ReleaseTag
  MYEMS_AGGREGATION_IMAGE = Get-ImageName -Repository 'aggregation' -Tag $ReleaseTag
  MYEMS_CLEANING_IMAGE = Get-ImageName -Repository 'cleaning' -Tag $ReleaseTag
  MYEMS_MODBUS_TCP_IMAGE = Get-ImageName -Repository 'modbus-tcp' -Tag $ReleaseTag
  MYEMS_MQTT_IMAGE = Get-ImageName -Repository 'mqtt' -Tag $ReleaseTag
  MYEMS_NORMALIZATION_IMAGE = Get-ImageName -Repository 'normalization' -Tag $ReleaseTag
  MYEMS_ADMIN_IMAGE = Get-ImageName -Repository 'admin' -Tag $ReleaseTag
  MYEMS_WEB_IMAGE = Get-ImageName -Repository 'web' -Tag $ReleaseTag
}

$customServices = @(
  'api',
  'aggregation',
  'cleaning',
  'modbus_tcp',
  'myems_mqtt',
  'normalization',
  'admin',
  'web'
)

$envFilePath = Join-Path $OutputDir 'docker-images.env'
$envFileLines = @(
  '# Generated by scripts/prebuild-release-images.ps1',
  "# Release tag: $ReleaseTag",
  "# Commit: $((git rev-parse HEAD).Trim())"
)

foreach ($entry in $imageMap.GetEnumerator()) {
  Set-Item -Path ("Env:{0}" -f $entry.Key) -Value $entry.Value
  $envFileLines += "{0}={1}" -f $entry.Key, $entry.Value
}

Set-Content -Path $envFilePath -Value $envFileLines -Encoding ascii

Write-Host "Using release tag: $ReleaseTag"
Write-Host "Writing image env file: $envFilePath"
Write-Host 'Building custom MyEMS images...'

& docker-compose -f $composeFile build @customServices

Write-Host "Pulling EMQX image: $EmqxImage"
& docker pull $EmqxImage

$allImages = @(
  $imageMap['MYEMS_API_IMAGE'],
  $imageMap['MYEMS_AGGREGATION_IMAGE'],
  $imageMap['MYEMS_CLEANING_IMAGE'],
  $imageMap['MYEMS_MODBUS_TCP_IMAGE'],
  $imageMap['MYEMS_MQTT_IMAGE'],
  $imageMap['MYEMS_NORMALIZATION_IMAGE'],
  $imageMap['MYEMS_ADMIN_IMAGE'],
  $imageMap['MYEMS_WEB_IMAGE'],
  $imageMap['MYEMS_EMQX_IMAGE']
)

foreach ($image in $allImages) {
  & docker image inspect $image | Out-Null
}

$manifestPath = Join-Path $OutputDir 'image-manifest.txt'
& docker image ls --format '{{.Repository}}:{{.Tag}} {{.ID}}' $allImages | Set-Content -Path $manifestPath -Encoding ascii

if (-not $SkipSave) {
  $tarPath = Join-Path $OutputDir ("myems-images-{0}.tar" -f $ReleaseTag)
  Write-Host "Exporting offline image package: $tarPath"
  & docker save -o $tarPath @allImages

  $hash = Get-FileHash -Path $tarPath -Algorithm SHA256
  $hashPath = Join-Path $OutputDir 'myems-images.sha256'
  Set-Content -Path $hashPath -Value ("{0} *{1}" -f $hash.Hash.ToLowerInvariant(), [System.IO.Path]::GetFileName($tarPath)) -Encoding ascii
}

Write-Host ''
Write-Host 'Release image prebuild completed.'
Write-Host "Artifacts directory: $OutputDir"
Write-Host "Compose env file: $envFilePath"
Write-Host 'Production usage:'
Write-Host '  1. Copy docker-images.env to the production others/ directory or adjust paths as needed.'
Write-Host '  2. If using offline delivery, transfer the tar file and run: docker load -i myems-images-<tag>.tar'
Write-Host '  3. Start services with: docker compose --env-file docker-images.env -f docker-compose-on-linux.image.yml up -d --no-build'