#!/usr/bin/env bash

set -euo pipefail

release_tag="${1:-}"
registry_prefix="${2:-}"
emqx_image="${3:-emqx/emqx:latest}"
output_file="${4:-}"

if [[ -z "$release_tag" ]]; then
  echo "usage: $0 <release-tag> <registry-prefix> [emqx-image] [output-file]" >&2
  exit 1
fi

if [[ -z "$registry_prefix" ]]; then
  echo "registry prefix is required" >&2
  exit 1
fi

if [[ -z "$output_file" ]]; then
  output_file="others/docker-images.env"
fi

registry_prefix="${registry_prefix%/}"
output_dir="$(dirname "$output_file")"
mkdir -p "$output_dir"

cat > "$output_file" <<EOF
# Generated by scripts/render-docker-images-env.sh
# Release tag: ${release_tag}
MYEMS_EMQX_IMAGE=${emqx_image}
MYEMS_API_IMAGE=${registry_prefix}/api:${release_tag}
MYEMS_AGGREGATION_IMAGE=${registry_prefix}/aggregation:${release_tag}
MYEMS_CLEANING_IMAGE=${registry_prefix}/cleaning:${release_tag}
MYEMS_MODBUS_TCP_IMAGE=${registry_prefix}/modbus-tcp:${release_tag}
MYEMS_MQTT_IMAGE=${registry_prefix}/mqtt:${release_tag}
MYEMS_NORMALIZATION_IMAGE=${registry_prefix}/normalization:${release_tag}
MYEMS_ADMIN_IMAGE=${registry_prefix}/admin:${release_tag}
MYEMS_WEB_IMAGE=${registry_prefix}/web:${release_tag}
EOF

echo "wrote $output_file"